image: mlpack/jenkins-amd64-cuda-11.2.2-ubuntu

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build-job
  - test-cuda
  - test-opencl

build-job:
  tags: [gpu]
  stage: build-job
  script: |
    ls
  artifacts:
    paths:
    - bandicoot-code

test-cuda:
  tags: [gpu]
  stage: test-cuda
  needs: ["build-job"]
  script: |
    cd tests
    make clean && BACKEND=CUDA_BACKEND make -j2
    export CUDA_VISIBLE_DEVICES=0
    ./main
    export CUDA_VISIBLE_DEVICES=1
    ./main
    export CUDA_VISIBLE_DEVICES=3
    ./main

test-opencl:
  tags: [gpu]
  stage: test-opencl
  needs: ["build-job"]
  script: |
    cd tests
    make clean && BACKEND=CL_BACKEND make -j2
    clinfo
    export CUDA_VISIBLE_DEVICES=0
    ./main
    export CUDA_VISIBLE_DEVICES=1
    ./main
    export CUDA_VISIBLE_DEVICES=3
    ./main
