image: mlpack/jenkins-amd64-cuda-11.2.2-ubuntu

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build-job
  - test-cuda
  - test-opencl

build-job:
  tags: [gpu]
  stage: build-job
  script: |
    ls
  artifacts:
    paths:
    - bandicoot-code

test-cuda:
  tags: [gpu]
  stage: test-cuda
  needs: ["build-job"]
  script: |
    mkdir build/
    cd build/
    cmake -DFIND_CUDA=ON -DFIND_OPENCL=OFF -DBUILD_TESTS=ON ../
    make -j2
    ./bandicoot_test

test-opencl:
  tags: [gpu]
  stage: test-opencl
  needs: ["build-job"]
  script: |
    mkdir build/
    cd build/
    cmake -DFIND_CUDA=OFF -DFIND_OPENCL=ON -DBUILD_TESTS=ON ../
    make -j2
    ./bandicoot_test
